version: "3.9"

# usage:

###### run local database, backend, and frontend
#  $ docker-compose --profile local up         

###### run local backend and frontend against a database in Couchbase Capella cloud
#  $ CB_HOST=cb.{your-host}.cloud.couchbase.com  docker-compose --profile capella up

###### run local database OR backend OR frontend in a mix-and match style
#  $ docker-compose up db

#  $ CB_HOST=...
#  $ CB_USER=...
#  $ CB_PSWD=...
#  # docker-compose up backend

#  $ docker-compose up frontend

###### run developer tests against the travel-sample backend
#  $ docker-compose up test        

services:
  db:
    image: couchbase/server-sandbox:7.1.0
    ports:
      - "8000-8005:8000-8005"
      - "9102:9102"
      - "11200:11200"
    expose:
      - "8001"
      - "8004"
    container_name: couchbase-sandbox-7.1.0
    profiles:
      - local
      - mix-and-match
      - test

  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    command: -c ${CB_HOST:-db} -u ${CB_USER:-Administrator} -p ${CB_PSWD:-password}
    volumes:
      - .:/app
    container_name: try-cb-api
    profiles:
      - local
      - mix-and-match
      - test

  capella-backend:
    build: .
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    entrypoint: ["python", "travel.py"]
    command: -c ${CB_HOST:-""} -u ${CB_USER:-cbdemo} -p "${CB_PSWD:-Password123!}" -s couchbases -a ?ssl=no_verify
    ports:
      - 8080:8080
    volumes:
      - .:/app
    container_name: try-cb-api-cap
    profiles:
      - capella

  frontend:
    build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
    ports:
      - 8081:8081
    container_name: try-cb-fe-mm
    profiles:
      - mix-and-match
            
  # frontend - Local frontend, depends on backend
  local-frontend:
      build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
      depends_on:
        - backend
      ports:
        - 8081:8081
      container_name: try-cb-fe
      entrypoint: ["wait-for-it", "backend:8080", "--timeout=400", "--strict", "--", "npm", "run", "serve"]
      profiles:
        - local

  capella-frontend:
      build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
      depends_on:
        - capella-backend
      ports:
        - 8081:8081
        
      container_name: try-cb-fe-cap
      entrypoint: ["wait-for-it", "capella-backend:8080", "--timeout=400", "--strict", "--", "npm", "run", "serve"]
      profiles:
        - capella
    
  test:
    build: "https://github.com/couchbaselabs/try-cb-test.git#main"
    depends_on:
      - db
      - backend
    environment:
      BACKEND_BASE_URL: http://backend:8080
    entrypoint: ["wait-for-it", "backend:8080", "--timeout=400", "--strict", "--", "bats", "travel-sample-backend.bats"]
    profiles:
      - test
